### ISSUE TITLE
Program crashing when parsing FASTQ

### ISSUE THREAD

**Issue by JeremyWearO** [drivenbyentropy/aptasuite#101]
I've been trying to get started with 0.9.4. I can run AptaSim and then perform all the applicable analysis on the simulated aptamer pools. However, I run into problems whenever I try to parse FASTQ files - the program crashes when I try to import the data. The log is as follows:

[12:35:44 | CONFIG | JavaFX Application Thread]: aptasuite.Aptasuite
System Information:
Java Version: 1.8.0_291
JavaFX Version: null
OS Name: Windows 10
OS Version: 10.0
OS Architecture: x86
OS Architecture Model: 32
CPU cores: 8
System Memory: 16252928 Mb
 

[12:35:44 | INFO | JavaFX Application Thread]: utilities.Version
AptaSuite version read from file. Version is 0.9.4 

[12:35:44 | WARNING | JavaFX Application Thread]: utilities.Version
Error checking for newer version 

[12:35:44 | CONFIG | JavaFX Application Thread]: utilities.Version
java.lang.NumberFormatException: For input string: "5b"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at utilities.Version.newerVersionAvailable(Version.java:124)
	at gui.core.RootClass.start(RootClass.java:55)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)
 

[12:35:44 | INFO | JavaFX Application Thread]: gui.wizards.newexperiment.WizardStartController
Starting New Experiment Wizard 

[12:35:44 | CONFIG | JavaFX Application Thread]: utilities.Configuration
Written Configuration file to C:\Users\path\to\folder\configuration.aptasuite 

[12:35:46 | INFO | Thread-5]: utilities.Configuration
Reading configuration from file. 

[12:35:46 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Creating Database 

[12:35:46 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
Error invoking construtor of AptamerPool backend 

[12:35:46 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
Error invoking AptamerPool backend

If there is anything obviously wrong here that would be good to know. I've tried it on multiple FASTQ files including real NGS files, self-made sample files, and those generated by AptaSim.

Thanks in advance for your help.

**Comment by drivenbyentropy** [comment]
I looks like you are trying to set the selection cycle number to an invalid input (5b). The selection cycle should be a single integer number (e.g. 5). If you have multiple pools for a particular selection round, you can distinguish between these by giving them different names and giving them all the same selection cycle integer.

Let me know if this solves the issue.

**Comment by JeremyWearO** [comment]
No, I don't think this is the case.

![image](https://user-images.githubusercontent.com/85597823/121461505-5a594300-c9f2-11eb-8d4c-4d64358e9d3e.png)

As you can see, I'm setting the selection cycle number to an integer in the GUI.

In all my logs (for all FASTQ files) I do get:

java.lang.NumberFormatException: For input string: "5b"

Plus the block that goes with it. I'm not sure where this would be coming from. There is nowhere that I am inputting '5b'.

Thanks for your help so far. Please let me know if you have any other insights.

**Comment by drivenbyentropy** [comment]
Could you please share your configuration file? It could help getting to the bottom of this. Thanks!

**Comment by JeremyWearO** [comment]
Here are the Config parameters:


Experiment.name = test
Experiment.description = test
Experiment.projectPath = C:\\Users\\user\\Documents\\AptaSuite\\verify\\trying again\\testingagain\\test
Experiment.primer5 = GGAGGCTCTCGGGACGAC
Experiment.primer3 = CGTCCCGATGCTGCAATCGTAA
Experiment.randomizedRegionSize = 32
AptaplexParser.isPerFile = true
AptaplexParser.reader = FastqReader
SelectionCycle.name = 1
SelectionCycle.round = 1
SelectionCycle.isControlSelection = false
SelectionCycle.isCounterSelection = false
AptaplexParser.forwardFiles = C:\\\\Users\\\\user\\\\Documents\\\\AptaSuite\\\\verify\\\\trying again\\\\testingagain\\\\Cycle0.fastq


I don't see anything wrong myself. Maybe you can see something. I might try installing and running the software on another PC.

Thanks again for your help

**Comment by drivenbyentropy** [comment]
Has this been fixed? Please feel free to reopen if the issue persists.
