### ISSUE TITLE
Aptasuite is running too long

### ISSUE THREAD

**Issue by EleEre** [drivenbyentropy/aptasuite#109]
The analysis of my data is taking too much time. 
I run the program for almost 24h and nothing appeared. I started the analysis from a trial of only one round of SELEX and 1 library, that has 2 files, forward and reverse sequences after MiSeq NGS sequencing. 

Is it normal?

Here is my logs data:
[3:26:33 | CONFIG | JavaFX Application Thread]: aptasuite.Aptasuite
System Information:
Java Version: 1.8.0_333
JavaFX Version: null
OS Name: Windows 10
OS Version: 10.0
OS Architecture: amd64
OS Architecture Model: 64
CPU cores: 8
System Memory: 257425408 Mb
 

[3:26:33 | INFO | JavaFX Application Thread]: utilities.Version
AptaSuite version read from file. Version is 0.9.8 

[3:26:33 | INFO | JavaFX Application Thread]: gui.wizards.newexperiment.WizardStartController
Starting New Experiment Wizard 

[3:26:33 | CONFIG | JavaFX Application Thread]: utilities.Configuration
Written Configuration file to C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\configuration.aptasuite 

[3:26:35 | INFO | Thread-5]: utilities.Configuration
Reading configuration from file. 

[3:26:35 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Creating Database 

[3:26:35 | INFO | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Instantiating MapDBAptamerPool 

[3:26:53 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Created new file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\data0000.mapdb 

[3:27:09 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Created new bounds file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\bounds_data0000.mapdb 

[3:27:27 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Created new inverse file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\data_inverse.mapdb 

[3:27:27 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
AptamerPool instantiation took 51.399 seconds 

[3:27:27 | INFO | Thread-5]: lib.aptamer.datastructures.MapDBSelectionCycle
Processing selection cycle Lib40-VHH-MTX 

[3:27:36 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBSelectionCycle
Creating new file 'C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\cycledata\8_Lib40-VHH-MTX.mapdb' for selection cycle Lib40-VHH-MTX. 

[3:27:36 | CONFIG | Thread-5]: lib.aptamer.datastructures.Metadata
Creating new Metadata instance. 

[3:27:36 | INFO | Thread-5]: lib.aptamer.datastructures.Experiment
Loading took 60894 milliseconds 

[3:27:36 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Initializing Experiment 

[3:27:36 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Initializing parser AptaplexParser 

[3:27:36 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Starting AptaPlex: 

[3:27:36 | CONFIG | pool-2-thread-1]: lib.parser.aptaplex.FastqReader
Opened forward file in fastq format C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Amplicon-Elena-R8-3_S18_L001_R1_001.fastq 

[3:27:36 | CONFIG | pool-2-thread-1]: lib.parser.aptaplex.FastqReader
Opened forward reverse in fastq format C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Amplicon-Elena-R8-3_S18_L001_R2_001.fastq 

[3:27:41 | CONFIG | pool-2-thread-1]: lib.parser.aptaplex.AptaPlexProducer
Added poison pill to parsing queue 

[3:27:41 | CONFIG | pool-2-thread-2]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-7]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-3]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-6]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-8]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-5]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | pool-2-thread-4]: lib.parser.aptaplex.AptaPlexConsumer
Encountered poison pill. Exiting thread. 

[3:27:41 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Closing pool file handles. 

[3:27:41 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Reopened as read only file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\data0000.mapdb 

[3:27:41 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Reopened as read only file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\inverse_data0000.mapdb 

[3:27:41 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBAptamerPool
Reopened as read only file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\pooldata\bounds_data0000.mapdb 

[3:27:42 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBSelectionCycle
Reopened as read only file C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\cycledata\8_Lib40-VHH-MTX.mapdb 

[3:27:42 | CONFIG | Thread-5]: lib.aptamer.datastructures.Metadata
Saved metadata to file 'C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\metadata.mapdb 

[3:27:42 | INFO | Thread-5]: lib.parser.aptaplex.AptaPlexParser
Parsing Completed, Data storage set to read-only and metadata written to file 

[3:27:42 | CONFIG | Thread-5]: gui.wizards.newexperiment.Wizard2Controller$1
Parsing Completed in 6.121 seconds.
 

[3:29:00 | CONFIG | JavaFX Application Thread]: utilities.Configuration
Written Configuration file to C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\configuration.aptasuite 

[3:29:00 | SEVERE | JavaFX Application Thread]: gui.core.RootLayoutController
javafx.fxml.LoadException: 
file:/C:/Users/eremeeve/Dropbox/@QUT/$Programs/aptasuite-0.9.8/aptasuite-0.9.8/aptasuite-0.9.8.jar!/gui/core/experiment/overview/ExperimentOverviewRandomizedRegionSizeDistribution.fxml
file:/C:/Users/eremeeve/Dropbox/@QUT/$Programs/aptasuite-0.9.8/aptasuite-0.9.8/aptasuite-0.9.8.jar!/gui/core/experiment/overview/ExperimentOverviewRoot.fxml:328

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1143)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
	at gui.core.RootLayoutController.addExperimentOverviewTab(RootLayoutController.java:607)
	at gui.core.RootLayoutController.lambda$showInitialTabs$5(RootLayoutController.java:313)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 22 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at gui.core.experiment.overview.ExperimentOverviewRandomizedRegionSizeDistributionController.computeStatistics(ExperimentOverviewRandomizedRegionSizeDistributionController.java:90)
	at gui.core.experiment.overview.ExperimentOverviewRandomizedRegionSizeDistributionController.initialize(ExperimentOverviewRandomizedRegionSizeDistributionController.java:55)
	... 32 more
 

[3:29:13 | INFO | Thread-44]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:29:13 | INFO | Thread-44]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:29:13 | INFO | Thread-44]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:29:13 | INFO | Thread-44]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:29:13 | INFO | Thread-44]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:29:22 | INFO | Thread-48]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:29:22 | INFO | Thread-48]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:29:22 | INFO | Thread-48]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:29:23 | INFO | Thread-48]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:29:23 | INFO | Thread-48]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:30:48 | INFO | Thread-54]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:30:48 | INFO | Thread-54]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:30:48 | INFO | Thread-54]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:30:48 | INFO | Thread-54]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:30:48 | INFO | Thread-54]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:30:52 | INFO | Thread-56]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:30:52 | INFO | Thread-56]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:30:52 | INFO | Thread-56]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:30:52 | INFO | Thread-56]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:30:52 | INFO | Thread-56]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:32:15 | INFO | Thread-60]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:32:15 | INFO | Thread-60]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:32:15 | INFO | Thread-60]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:32:16 | INFO | Thread-60]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:32:16 | INFO | Thread-60]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:32:32 | INFO | JavaFX Application Thread]: gui.core.motifs.MotifAnalysisRootController
Initializing Motif Analysis Content 

[3:32:35 | INFO | Thread-62]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:32:35 | INFO | Thread-62]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:32:35 | INFO | Thread-62]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:32:36 | INFO | Thread-62]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:32:36 | INFO | Thread-62]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[3:39:12 | INFO | Thread-66]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[3:39:12 | INFO | Thread-66]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[3:39:12 | INFO | Thread-66]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[3:39:13 | INFO | Thread-66]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[3:39:13 | INFO | Thread-66]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:02:30 | INFO | Thread-70]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:02:30 | INFO | Thread-70]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:02:30 | INFO | Thread-70]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:02:31 | INFO | Thread-70]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:02:31 | INFO | Thread-70]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:02:32 | INFO | JavaFX Application Thread]: gui.core.motifs.MotifAnalysisRootController
Initializing Motif Analysis Content 

[4:02:35 | INFO | Thread-72]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:02:35 | INFO | Thread-72]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:02:35 | INFO | Thread-72]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:02:36 | INFO | Thread-72]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:02:36 | INFO | Thread-72]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:23:12 | INFO | Thread-76]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:23:12 | INFO | Thread-76]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:23:12 | INFO | Thread-76]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:23:12 | INFO | Thread-76]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:23:12 | INFO | Thread-76]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:26:29 | INFO | Thread-80]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:26:29 | INFO | Thread-80]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:26:29 | INFO | Thread-80]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:26:30 | INFO | Thread-80]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:26:30 | INFO | Thread-80]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:35:07 | INFO | Thread-82]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:35:07 | INFO | Thread-82]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:35:07 | INFO | Thread-82]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:35:08 | INFO | Thread-82]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:35:08 | INFO | Thread-82]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[4:51:08 | INFO | Thread-84]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[4:51:08 | INFO | Thread-84]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[4:51:08 | INFO | Thread-84]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[4:51:09 | INFO | Thread-84]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[4:51:09 | INFO | Thread-84]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[5:08:15 | INFO | Thread-86]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[5:08:15 | INFO | Thread-86]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[5:08:15 | INFO | Thread-86]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[5:08:15 | INFO | Thread-86]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[5:08:15 | INFO | Thread-86]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[9:37:55 | INFO | Thread-88]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[9:37:55 | INFO | Thread-88]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[9:37:55 | INFO | Thread-88]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[9:37:55 | INFO | Thread-88]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[9:37:55 | INFO | Thread-88]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[10:13:02 | INFO | Thread-90]: gui.wizards.export.ExportWizardController$2
Checking for cluster information 

[10:13:12 | CONFIG | Thread-90]: lib.aptamer.datastructures.MapDBClusterContainer
Reading from file 'C:\Users\eremeeve\Dropbox\@QUT\Sequencing\NGS_sequencing\2022_05_07\Trial\clusterdata\clusters.mapdb' for cluster storage. 

[10:13:12 | SEVERE | Thread-90]: lib.aptamer.datastructures.Experiment
Error invoking construtor of ClusterContainer backend 

[10:13:12 | SEVERE | Thread-90]: lib.aptamer.datastructures.Experiment
Error invoking ClusterContainer backend 

[10:13:12 | INFO | Thread-90]: gui.wizards.export.ExportWizardController$2
Did not find cluster information 

[10:13:20 | INFO | Thread-93]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[10:13:20 | INFO | Thread-93]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[10:13:20 | INFO | Thread-93]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[10:13:21 | INFO | Thread-93]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[10:13:21 | INFO | Thread-93]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[10:13:25 | INFO | Thread-95]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[10:13:25 | INFO | Thread-95]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[10:13:25 | INFO | Thread-95]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle Lib40-VHH-MTX 

[10:13:25 | INFO | Thread-95]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[10:13:25 | INFO | Thread-95]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data

**Comment by EleEre** [comment]
![error](https://user-images.githubusercontent.com/106126394/169928699-1759c9bd-b6fb-4d4f-ba0a-b5f034236b47.JPG)

**Comment by EleEre** [comment]
It tried with another Library, round and therefore files and got the same issue. Everything stuck on sorting data as on the picture above

**Comment by EleEre** [comment]
Could you please answer my question?

**Comment by EleEre** [comment]
Figured it out!

Thank you

**Comment by solracTV** [comment]
Hey EleEre, I'm having the same issue, could you tell me how you fixed yours?

**Comment by EleEre** [comment]
Hey solracTV, You should use only one read type at a time, so only forward or only reverse one for all sequences uploaded.
here I found an example
<img width="894" alt="image" src="https://user-images.githubusercontent.com/106126394/171785319-f62585f0-98be-49dd-8f84-bd42e2716fba.png">
![NGS tips](https://user-images.githubusercontent.com/106126394/171785437-f1227afe-1698-4f4d-9fa0-e14123be2e49.jpg)
