### ISSUE TITLE
Issue exporting clusters: exception in thread "main"

### ISSUE THREAD

**Issue by kep93943** [drivenbyentropy/aptasuite#114]
Parsing and exporting the pool and cycle files goes smoothly, but once it reaches exporting clusters the following error appears.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at utilities.Quicksort.quicksort(Quicksort.java:94)
	at utilities.Quicksort.sort(Quicksort.java:44)
	at lib.export.Export.ClustersBySize(Export.java:558)
	at lib.export.Export.Clusters(Export.java:279)
	at aptasuite.CLI.exportData(CLI.java:1096)
	at aptasuite.CLI.<init>(CLI.java:280)
	at aptasuite.Aptasuite.main(Aptasuite.java:70)

**Comment by kep93943** [comment]
The problem appears to be that the naive library file did not contain any clusters that were made up of more than one sequence (meaning no clusters...). My configuration file had a minimum cluster size of 2, so it immediately ran into this issue. This was then easily fixed by changing the minimum cluster size to 1.
