### ISSUE TITLE
Open Java Bug

### ISSUE THREAD

**Issue by sonatabio** [drivenbyentropy/aptasuite#44]
I tried to run AptaSuite on a FreeBSD VM running under Windows.  FreeBSD natively runs Open Java.  I obtained the following error message (version information given below):

<blockquote>NGS@NGS:~/AptaSuite/aptasuite-0.8.4 % java -jar aptasuite-0.8.4.jar

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at aptasuite.Aptasuite.main(Aptasuite.java:86)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
</blockquote>
<blockquote>
NGS@NGS:~/AptaSuite/aptasuite-0.8.4 % java -version

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
</blockquote><blockquote>
NGS@NGS:~/AptaSuite/aptasuite-0.8.4 % uname -a
FreeBSD NGS.sonatabio.com 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
NGS@NGS:~/AptaSuite/aptasuite-0.8.4 % 
</blockquote>

Edit to clean up formatting.

**Comment by drivenbyentropy** [comment]
Hi,

The error 
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
```
suggests that you are missing the `openjfx8` dependency on your system. Please install open JavaFX and try to run AptaSuite again. 

Thanks for reporting this!

**Comment by sonatabio** [comment]
That worked -- thanks.  I only loaded the opening screen, but I assume that the rest of it works as expected.

FWIW, I had to recompile xorg, so it took a while!

You may wish to add this library to the list of requirements.

**Comment by drivenbyentropy** [comment]
Glad to hear the issue is solved. I have added a link to the extended [system requirements](https://github.com/drivenbyentropy/aptasuite/wiki/System-Requirements) describing the JavaFX dependency to the `readme.md`. 

Thanks again!
