### ISSUE TITLE
java issue

### ISSUE THREAD

**Issue by samoudj** [drivenbyentropy/aptasuite#68]
Hello, I got an error while executing the command: 

 java -jar aptasuite-0.9.4.jar

the error is
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

thank you for your answers

**Comment by drivenbyentropy** [comment]
Hi, thank you for reporting this. 

What Java version do you have? I cannot reproduce this error locally. Please make sure you adhere to the system requirement outlined [here.](https://github.com/drivenbyentropy/aptasuite/wiki/System-requirements). 

Please let me know if this does not solve your issue. Thanks!

**Comment by samoudj** [comment]
Hello, can you please help a little more, I really installed everything but
still the same error

Le mar. 9 avr. 2019 à 10:27, drivenbyentropy <notifications@github.com> a
écrit :

**Comment by drivenbyentropy** [comment]
Can you run the following command and paste the output?

```java -verbose:class -jar aptasuite-0.9.4.jar | grep commons-cli```

Thanks!

**Comment by samoudj** [comment]
same error

Error: A JNI error has occurred, please check your installation and try
again
Exception in thread "main" java.lang.NoClassDefFoundError:
org/apache/commons/cli/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at
sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at
sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException:
org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more


Le mar. 9 avr. 2019 à 22:39, drivenbyentropy <notifications@github.com> a
écrit :

**Comment by drivenbyentropy** [comment]
I am not sure how to proceed from here as I cannot reproduce this issue on any of my development machines. Do you have a secondary computer you could try this on? Again, this issue points to a faulty Java installation which is out of the scope of this project. 

One thing I noticed, is that you are running `OpenJDK`. You could try to install Oracles Java implementation. There are many howtos online on how to do this for Ubuntu. 

I hope this helps.

**Comment by samoudj** [comment]
i installed oracle-java8-installer
maven 3.3.9
openjfx

But still have the same error, could at list give what i have to install
with the good order

Le mer. 10 avr. 2019 à 10:42, drivenbyentropy <notifications@github.com> a
écrit :

**Comment by drivenbyentropy** [comment]
Given that you mention Maven, are you trying to compile the project from source? If so, I would recommend against this as we provide precompiled versions of AptaSuite on the [release page](https://github.com/drivenbyentropy/aptasuite/releases/download/v0.9.4/aptasuite-0.9.4.zip).

You should only require to extract the archive and run it, the prerequisites of which are either Oracles Java 1.8 or higher (which ships JavaFX) or openJDK + openJFX.

**Comment by samoudj** [comment]
Excellent!! it finally worked, I think the problem was with the
compilation, thank you very very much

Le mer. 10 avr. 2019 à 13:18, drivenbyentropy <notifications@github.com> a
écrit :

**Comment by drivenbyentropy** [comment]
Glad to hear!
