### ISSUE TITLE
Issue in running the AptaSuite program

### ISSUE THREAD

**Issue by psomdeb25** [drivenbyentropy/aptasuite#80]
Hello. I downloaded the pre-compiled version and extracted it using the tar command. After which I tried running using: java -jar aptasuite-0.9.4.jar. However, I am presented with errors which I wasn't really able to understand.

This is error that shows up on first running the program:

`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at aptasuite.Aptasuite.main(Aptasuite.java:89)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more`

So, I ran with verbose (-v) flag and this shows up:
`Unrecognized option: -v
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

Is there any missing dependencies?

**Comment by psomdeb25** [comment]
I forgot to mention that I am running macOS v 10.14.6

**Comment by Bioanalytica** [comment]
Are you sure that you are running the correct version of Java and that it was installed correctly (is written into PATH)? I'm using Version 8.0.202.8

**Comment by psomdeb25** [comment]
@Bioanalytica This is the java version that I am running - 
`java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)`

But it came built into my OS.

**Comment by drivenbyentropy** [comment]
The error suggests that JavaFX is not present on your system. I do not have a Mac available but I suspect JavaFX does not ship with the Java version installed on your computer. 

You could start [here](https://gluonhq.com/products/javafx/) and check the installation instructions specific to your environment.

**Comment by drivenbyentropy** [comment]
I am closing this issue due to inactivity. Feel free to reopen should the problem persist.
