### ISSUE TITLE
aptamer pool tab hanging

### ISSUE THREAD

**Issue by nl82** [drivenbyentropy/aptasuite#81]
Hello,

I was able to parse the fastq files in aptasuite v.0.9.4. (the gui) but afterwards, the aptamer pool tab keeps calculating without showing any data. I got the following log in return.
Any help is much appreciated.

[10:57:26 | INFO | JavaFX Application Thread]: gui.wizards.newexperiment.WizardStartController
Starting New Experiment Wizard 

[10:57:26 | CONFIG | JavaFX Application Thread]: utilities.Configuration
Written Configuration file to /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/configuration.aptasuite 

[10:57:29 | INFO | Thread-28]: utilities.Configuration
Reading configuration from file. 

[10:57:29 | CONFIG | Thread-28]: gui.wizards.newexperiment.Wizard2Controller$1
Creating Database 

[10:57:30 | INFO | Thread-28]: lib.aptamer.datastructures.MapDBAptamerPool
Instantiating MapDBAptamerPool 

[10:57:33 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBAptamerPool
Created new file /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/pooldata/data0000.mapdb 

[10:57:36 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBAptamerPool
Created new bounds file /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/pooldata/bounds_data0000.mapdb 

[10:57:39 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBAptamerPool
Created new inverse file /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/pooldata/data_inverse.mapdb 

[10:57:39 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBAptamerPool
AptamerPool instantiation took 9.356 seconds 

[10:57:39 | INFO | Thread-28]: lib.aptamer.datastructures.MapDBSelectionCycle
Processing selection cycle sel_N_4_r1 

[10:57:42 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBSelectionCycle
Creating new file '/Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/cycledata/1_sel_N_4_r1.mapdb' for selection cycle sel_N_4_r1. 

[10:57:42 | INFO | Thread-28]: lib.aptamer.datastructures.MapDBSelectionCycle
Processing selection cycle sel_N_4_r2 

[10:57:45 | CONFIG | Thread-28]: lib.aptamer.datastructures.MapDBSelectionCycle
Creating new file '/Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/cycledata/2_sel_N_4_r2.mapdb' for selection cycle sel_N_4_r2. 

[10:57:45 | CONFIG | Thread-28]: lib.aptamer.datastructures.Metadata
Creating new Metadata instance. 

[10:57:45 | INFO | Thread-28]: lib.aptamer.datastructures.Experiment
Loading took 15996 milliseconds 

[10:57:45 | CONFIG | Thread-28]: gui.wizards.newexperiment.Wizard2Controller$1
Initializing Experiment 

[10:57:45 | CONFIG | Thread-28]: gui.wizards.newexperiment.Wizard2Controller$1
Initializing parser AptaplexParser 

[10:57:45 | CONFIG | Thread-28]: gui.wizards.newexperiment.Wizard2Controller$1
Starting AptaPlex: 

[10:57:45 | CONFIG | pool-3-thread-1]: lib.parser.aptaplex.FastqReader
Opened forward file in fastq format /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/sel_N_4_r1.fastq 

[10:57:48 | CONFIG | JavaFX Application Thread]: utilities.Configuration
Written Configuration file to /Users/m/Desktop/Aptasuit HT-SELEX/sel_N_4/selexN4/configuration.aptasuite 

[10:57:48 | SEVERE | JavaFX Application Thread]: gui.core.RootLayoutController
javafx.fxml.LoadException: 
file:/Users/m/Downloads/aptasuite-0.9.4/aptasuite-0.9.4.jar!/gui/core/experiment/overview/ExperimentOverviewRandomizedRegionSizeDistribution.fxml
file:/Users/m/Downloads/aptasuite-0.9.4/aptasuite-0.9.4.jar!/gui/core/experiment/overview/ExperimentOverviewRoot.fxml:328

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1143)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
	at gui.core.RootLayoutController.addExperimentOverviewTab(RootLayoutController.java:607)
	at gui.core.RootLayoutController.lambda$showInitialTabs$5(RootLayoutController.java:313)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 19 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at gui.core.experiment.overview.ExperimentOverviewRandomizedRegionSizeDistributionController.computeStatistics(ExperimentOverviewRandomizedRegionSizeDistributionController.java:90)
	at gui.core.experiment.overview.ExperimentOverviewRandomizedRegionSizeDistributionController.initialize(ExperimentOverviewRandomizedRegionSizeDistributionController.java:55)
	... 29 more
 

[10:57:53 | INFO | Thread-47]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[10:57:53 | INFO | Thread-47]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[10:57:53 | INFO | Thread-47]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle sel_N_4_r2 

[10:57:53 | INFO | Thread-47]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[10:57:53 | INFO | Thread-47]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data 

[10:58:11 | INFO | Thread-51]: gui.core.aptamer.pool.AptamerPoolRootController$1
Initializing data structures 

[10:58:11 | INFO | Thread-51]: gui.core.aptamer.pool.AptamerPoolRootController
Preparing to sort data 

[10:58:11 | INFO | Thread-51]: gui.core.aptamer.pool.AptamerPoolRootController
Retrieving data for selection cycle sel_N_4_r2 

[10:58:12 | INFO | Thread-51]: gui.core.aptamer.pool.AptamerPoolRootController
Prioritizing data 

[10:58:12 | INFO | Thread-51]: gui.core.aptamer.pool.AptamerPoolRootController
Sorting data

**Comment by Bioanalytica** [comment]
What operating system and version of Java JDK, Java JRE, & JavaFX are installed? I don't know what the optimal/maximum is but I'm running jdk-8u251, jre-8u251, & javafx_sdk-1_3_1-b05a.

I got the following output:

> Parsing Completed in 1050.158 seconds.

Selection Cycle Statistics
RME-AptaLib
RME-Round1-Pos
RME-Round2-Pos
RME-Round2-Neg
RME-Round3-Pos
RME-Round3-NegB
RME-Round4-Pos
RME-Round5-Pos
Starting Structure Predition
Using existing sequencing data
Instantiating MapDBStructurePool
Starting Structure Prediction using 24 threads:
Predicting...
