### ISSUE TITLE
precompiled Aptasuite 0.9.4 

### ISSUE THREAD

**Issue by mengops** [drivenbyentropy/aptasuite#87]
I am running aptasuite from the precompiled .jar file. When trying to start a new experiment the window opens up fine but the content does not fit. Therefore some parts of the windows are not visible. I tried to use tab and the pointers to move around or even scrolling but nothing happened. As it is, I can't launch any experiment on any of the platforms. Is there a way to fix it or should I just give up and use the command line option?

this is the only warning the code shows :

```
(java:72904): Gtk-WARNING **: 12:02:32.266: Unable to locate theme engine in module_path: "pixm
Gtk-Message: 12:02:32.272: Failed to load module "canberra-gtk-module"
```

Many thanks in advance for your help

**Comment by drivenbyentropy** [comment]
Thank you for the report. Could you attach a screenshot of the issue you are facing? 

What is the current screen resolution of your system? Thanks!

**Comment by mengops** [comment]
![aptasuite](https://user-images.githubusercontent.com/55202418/81306202-7f58e500-907f-11ea-9e28-f9c5442dd2c6.png)

The screenshot is attached and the resolution is 800x600.

many thanks for yout help and quick reply

**Comment by drivenbyentropy** [comment]
Thanks. AptaSuite requires a resolution of at least 1024x768 to fit all its content. Please try to adjust the resolution of your OS and see if that solves the issue.

**Comment by mengops** [comment]
Hi that solved the issue! Many thanks!
May I ask advice on another issue? I tried launching the analysis and the job failed. The window closed and the cmd shows the following error

`May 07, 2020 4:34:38 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.121
Reading configuration from file.
Error invoking construtor of AptamerPool backend
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at lib.aptamer.datastructures.Experiment.<init>(Experiment.java:147)
	at gui.wizards.newexperiment.Wizard2Controller$1.call(Wizard2Controller.java:155)
	at gui.wizards.newexperiment.Wizard2Controller$1.call(Wizard2Controller.java:141)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.BitSet.initWords(BitSet.java:166)
	at java.util.BitSet.<init>(BitSet.java:161)
	at orestes.bloomfilter.memory.BloomFilterMemory.<init>(BloomFilterMemory.java:15)
	at orestes.bloomfilter.FilterBuilder.buildBloomFilter(FilterBuilder.java:313)
	at lib.aptamer.datastructures.MapDBAptamerPool.<init>(MapDBAptamerPool.java:98)
	... 10 more
Error invoking AptamerPool backen`

attached you have the log file
[log_2020-05-07_16-34-38.txt](https://github.com/drivenbyentropy/aptasuite/files/4593627/log_2020-05-07_16-34-38.txt)

Could you advise me on what is the issue to be solved?

**Comment by drivenbyentropy** [comment]
`Caused by: java.lang.OutOfMemoryError: Java heap space at java.util.BitSet.initWords(BitSet.java:166) at java.util.BitSet.<init>(BitSet.java:161) at orestes.bloomfilter.memory.BloomFilterMemory.<init>(BloomFilterMemory.java:15)` 

You are running out of memory. If this is a virtual machine, try increasing the memory available to it and also make sure that AptaSuite can use it by setting the maximum allowed memory for Java. [See the FAQ for more information.](https://github.com/drivenbyentropy/aptasuite/wiki/Frequent-issues)
